title: "name of the artist"
labels: ["General Introduction"]
body:
  - type: input
    id: has-id
    attributes:
      label: Link to the image
      description: twitter or bluesky only examples of the type of link https://x.com/Jumngee/status/1817877737547210759,https://bsky.app/profile/aw-gazzam.bsky.social/post/3ljv7ejkkwc2k
    validations:
      required: true
  - type: dropdown
    id: download
    attributes:
      label: Type of image fictional,cosplay
      options:
        - Fictional
        - Cosplay
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Check that box!
      options:
        - label: This one!
          required: true
        - label: I won't stop you if you check this one, too
  - type: markdown
    attributes:
      value: |
        ### The thrilling conclusion
        _to our template_
